# In-class transcript from lecture 4, Oct 5, 2021


In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2021-fall/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

##########################################################
# If this import for matplotlib doesn't work, try saying #
#   conda install -c conda-forge ipympl                  #
# at a shell prompt on your computer                     #
##########################################################
import matplotlib
%matplotlib ipympl

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d




np.set_printoptions(precision = 4)

# Lower triangular matrix

In [2]:
A = np.round(10*np.random.random((4,4)))
print("A:\n", A)

A:
 [[9. 8. 8. 3.]
 [6. 4. 2. 4.]
 [4. 3. 8. 9.]
 [3. 6. 5. 2.]]


In [3]:
L = np.tril(A)
print("L:\n", L)

L:
 [[9. 0. 0. 0.]
 [6. 4. 0. 0.]
 [4. 3. 8. 0.]
 [3. 6. 5. 2.]]


# Unit lower triangular matrix

In [4]:
L = np.array([[1,0,0,0], [1,1,0,0], [2,0,1,0], [-1,2,1,1]])
print("L:\n", L)

L:
 [[ 1  0  0  0]
 [ 1  1  0  0]
 [ 2  0  1  0]
 [-1  2  1  1]]


# Unit lower triangular solve

In [5]:
b = np.array([2,3,3,1])
print("b:", b)

b: [2 3 3 1]


In [6]:
x = npla.solve(L,b)
print("x:", x)

x: [ 2.  1. -1.  2.]


In [8]:
cs111.Lsolve(L,b)

array([ 2.,  1., -1.,  2.])

In [7]:
print(L @ x)

[2. 3. 3. 1.]


<b>L is an n-by-n unit lower triangular matrix, and b is an n-vector.<br>
What's the asymptotic complexity of x = cs111.Lsolve(L, b), as O(...)?

# Permuting a vector

In [9]:
# Here's a vector we can practice on, with n = 5

v = np.array([3.1, 4.1, 5.9, 2.6, 5.3])
print("v:", v)

v: [3.1 4.1 5.9 2.6 5.3]


In [10]:
# Here's our example of a 5-permutation p (lower case p)

p = [3, 0, 4, 1, 2]
print("p:", p)

p: [3, 0, 4, 1, 2]


In [11]:
# Permute the vector with the permutation

print("v[p]:", v[p])

v[p]: [2.6 3.1 5.3 4.1 5.9]


In [12]:
# Here's our example of a 5-by-5 permutation matrix P (upper case P)

P = np.array([[0,0,0,1,0], [1,0,0,0,0], [0,0,0,0,1], [0,1,0,0,0], [0,0,1,0,0]])

print(P)

[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [13]:
# Permute the vector with the matrix

print("P @ v:", P @ v)

P @ v: [2.6 3.1 5.3 4.1 5.9]


In [14]:
# Here's another permutation we'll call pinv:

pinv = [1, 3, 4, 0, 2]
print("pinv:", pinv)

pinv: [1, 3, 4, 0, 2]


In [15]:
# Permute the vector with pinv -- it's different

print("v:      ", v)
print("v[p]:   ", v[p])
print("v[pinv]:", v[pinv])

v:       [3.1 4.1 5.9 2.6 5.3]
v[p]:    [2.6 3.1 5.3 4.1 5.9]
v[pinv]: [4.1 2.6 5.3 3.1 5.9]


In [16]:
# pinv is the inverse permutation of p

vp = v[p]
w = vp[pinv]
print('v[p][pinv]:', w)

v[p][pinv]: [3.1 4.1 5.9 2.6 5.3]


In [17]:
v[p][pinv]

array([3.1, 4.1, 5.9, 2.6, 5.3])

In [18]:
# How do we get the  matrix for the inverse permutation?
# It's just the transpose!

P

array([[0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [19]:
P.T

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [20]:
print("v[pinv]:", v[pinv])
print("P.T @ v:", P.T @ v)

v[pinv]: [4.1 2.6 5.3 3.1 5.9]
P.T @ v: [4.1 2.6 5.3 3.1 5.9]


In [23]:
print("P.T @ P @ v:", P.T @ P @ v)

P.T @ P @ v: [3.1 4.1 5.9 2.6 5.3]


In [21]:
# The matrix of the inverse perm is also the inverse matrix!

P.T @ P

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
P @ P.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Permuting a matrix

In [24]:
# Let's get a 5-by-5 matrix to experiment with

A = (20*np.random.random((5,5))).round()

A

array([[ 6.,  6., 10., 12.,  1.],
       [15.,  6.,  2., 17.,  7.],
       [ 9., 19.,  3., 17., 18.],
       [ 9.,  9., 11., 10.,  9.],
       [ 9., 13.,  2., 10., 18.]])

In [25]:
# Permute the rows of A with the permutation

print("p:", p)

p: [3, 0, 4, 1, 2]


In [26]:
A[p,:]

array([[ 9.,  9., 11., 10.,  9.],
       [ 6.,  6., 10., 12.,  1.],
       [ 9., 13.,  2., 10., 18.],
       [15.,  6.,  2., 17.,  7.],
       [ 9., 19.,  3., 17., 18.]])

In [27]:
# Permute the rows of A with the permutation matrix

P

array([[0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [28]:
P @ A

array([[ 9.,  9., 11., 10.,  9.],
       [ 6.,  6., 10., 12.,  1.],
       [ 9., 13.,  2., 10., 18.],
       [15.,  6.,  2., 17.,  7.],
       [ 9., 19.,  3., 17., 18.]])

In [29]:
A

array([[ 6.,  6., 10., 12.,  1.],
       [15.,  6.,  2., 17.,  7.],
       [ 9., 19.,  3., 17., 18.],
       [ 9.,  9., 11., 10.,  9.],
       [ 9., 13.,  2., 10., 18.]])

In [30]:
# Permute the columns of A with p

A[:,p]

array([[12.,  6.,  1.,  6., 10.],
       [17., 15.,  7.,  6.,  2.],
       [17.,  9., 18., 19.,  3.],
       [10.,  9.,  9.,  9., 11.],
       [10.,  9., 18., 13.,  2.]])

In [32]:
A[p,:][:,p]

array([[10.,  9.,  9.,  9., 11.],
       [12.,  6.,  1.,  6., 10.],
       [10.,  9., 18., 13.,  2.],
       [17., 15.,  7.,  6.,  2.],
       [17.,  9., 18., 19.,  3.]])

In [33]:
A[:,p]

array([[12.,  6.,  1.,  6., 10.],
       [17., 15.,  7.,  6.,  2.],
       [17.,  9., 18., 19.,  3.],
       [10.,  9.,  9.,  9., 11.],
       [10.,  9., 18., 13.,  2.]])

In [34]:
# Multiplying A on the right by P affects the columns of A ...
A @ P

array([[ 6., 12.,  1.,  6., 10.],
       [ 6., 17.,  7., 15.,  2.],
       [19., 17., 18.,  9.,  3.],
       [ 9., 10.,  9.,  9., 11.],
       [13., 10., 18.,  9.,  2.]])

In [35]:
A

array([[ 6.,  6., 10., 12.,  1.],
       [15.,  6.,  2., 17.,  7.],
       [ 9., 19.,  3., 17., 18.],
       [ 9.,  9., 11., 10.,  9.],
       [ 9., 13.,  2., 10., 18.]])

In [36]:
# ... But that's not the column permutation we wanted!

# We need to use P.T on the right if we used P on the left

A @ P.T

array([[12.,  6.,  1.,  6., 10.],
       [17., 15.,  7.,  6.,  2.],
       [17.,  9., 18., 19.,  3.],
       [10.,  9.,  9.,  9., 11.],
       [10.,  9., 18., 13.,  2.]])

# Building the temperature matrix

## Small example: k = 4, n = 16 unknowns

In [ ]:
cs111.make_A_small?

In [37]:
A = cs111.make_A_small()
print(A)

[[ 4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0. -1.  4.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  4. -1.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4. 

## Matrix A is sparse (mostly zeros)

In [39]:
A.shape

(16, 16)

In [40]:
np.count_nonzero(A)

64

In [38]:
b = cs111.make_b_small()
print(b)

[ 64. 212.  32.  64.  32.   0.   0.  32.  32.   0.   0.  32.  64.  32.
  32.  64.]


In [41]:
x = npla.solve(A,b)

In [42]:
x.shape

(16,)

In [43]:
print(x)

[50.3818 93.0364 52.7818 38.8455 44.4909 56.9818 47.2455 38.6    38.6
 43.1545 40.6182 36.3091 34.7545 36.4182 35.7636 34.0182]


In [44]:
T = x.reshape(4,4)
print(T)

[[50.3818 93.0364 52.7818 38.8455]
 [44.4909 56.9818 47.2455 38.6   ]
 [38.6    43.1545 40.6182 36.3091]
 [34.7545 36.4182 35.7636 34.0182]]


In [45]:
plt.figure()
plt.imshow(T, cmap=cm.hot)
plt.xlabel('x0')
plt.ylabel('x1')
plt.title('2-dimensional Poisson equation (temperature)')

FigureCanvasNbAgg()

Text(0.5,1,'2-dimensional Poisson equation (temperature)')

## Large example, k = 100 (so n = 10,000), using sparse data structure

In [46]:
k = 100
A = cs111.make_A(k)
b = cs111.make_b(k, top = cs111.radiator(k))

In [47]:
A.shape

(10000, 10000)

In [48]:
x = scipy.sparse.linalg.spsolve(A,b) # ugly!

In [49]:
x.shape

(10000,)

In [50]:
T = x.reshape(k, k)
plt.figure()
plt.imshow(T, cmap=cm.hot)
plt.xlabel('x0')
plt.ylabel('x1')
plt.title('2-dimensional Poisson equation (temperature)')

FigureCanvasNbAgg()

Text(0.5,1,'2-dimensional Poisson equation (temperature)')