# In-class transcript from Lecture 3, September 30, 2021

The first window below does the standard imports for CS 111. The list may change as the quarter goes on.

You should change the string in **sys.path.append()** to be the full path on your own computer to the **CS111-2021-fall/Python** directory that you got when you cloned **CS111-2021-fall** to your computer from GitHub.

In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2021-fall/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

# If this import for matplotlib doesn't work, try saying 
#   conda install -c conda-forge ipympl
# at a shell prompt on your computer

import matplotlib
%matplotlib ipympl
import matplotlib.pyplot as plt

np.set_printoptions(precision = 4)

# Matrices in numpy

In [2]:
S = np.array([[2,-1],[-1,2]])
S

array([[ 2, -1],
       [-1,  2]])

In [3]:
print(S)

[[ 2 -1]
 [-1  2]]


In [4]:
b = np.array([0,3])
b

array([0, 3])

In [5]:
x = npla.solve(S,b)
x

array([1., 2.])

In [6]:
S @ x 

array([0., 3.])

In [7]:
S

array([[ 2, -1],
       [-1,  2]])

In [8]:
S + 3

array([[5, 2],
       [2, 5]])

In [9]:
S / 2

array([[ 1. , -0.5],
       [-0.5,  1. ]])

In [10]:
S + S

array([[ 4, -2],
       [-2,  4]])

In [11]:
np.sin(S)

array([[ 0.9093, -0.8415],
       [-0.8415,  0.9093]])

In [12]:
R = np.arange(16)
R

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
list(range(16))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [14]:
R.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
R.reshape?

In [16]:
R

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
R[5]

5

In [18]:
R = R * R
R

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [19]:
R[5]

25

In [20]:
R[4:8]

array([16, 25, 36, 49])

In [21]:
R[:8]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [22]:
R[6:]

array([ 36,  49,  64,  81, 100, 121, 144, 169, 196, 225])

In [23]:
R[2:12:2]

array([  4,  16,  36,  64, 100])

In [24]:
R[::-1]

array([225, 196, 169, 144, 121, 100,  81,  64,  49,  36,  25,  16,   9,
         4,   1,   0])

In [25]:
A = np.random.random((4,4))

In [26]:
A

array([[0.3375, 0.5757, 0.3208, 0.0836],
       [0.9344, 0.582 , 0.0179, 0.9613],
       [0.5677, 0.4039, 0.7327, 0.4279],
       [0.7739, 0.9189, 0.3118, 0.2062]])

In [27]:
A = np.round(100*A)

In [28]:
A

array([[34., 58., 32.,  8.],
       [93., 58.,  2., 96.],
       [57., 40., 73., 43.],
       [77., 92., 31., 21.]])

In [29]:
A[2,3]

43.0

In [30]:
A[2,:]

array([57., 40., 73., 43.])

In [31]:
A[2,::-1]

array([43., 73., 40., 57.])

In [32]:
A[::-1,::-1]

array([[21., 31., 92., 77.],
       [43., 73., 40., 57.],
       [96.,  2., 58., 93.],
       [ 8., 32., 58., 34.]])

In [33]:
A

array([[34., 58., 32.,  8.],
       [93., 58.,  2., 96.],
       [57., 40., 73., 43.],
       [77., 92., 31., 21.]])

In [34]:
A[2,0] = 3
A

array([[34., 58., 32.,  8.],
       [93., 58.,  2., 96.],
       [ 3., 40., 73., 43.],
       [77., 92., 31., 21.]])

In [35]:
A[[0,1],:] = A[[1,0], :]

In [36]:
A

array([[93., 58.,  2., 96.],
       [34., 58., 32.,  8.],
       [ 3., 40., 73., 43.],
       [77., 92., 31., 21.]])

In [37]:
- A

array([[-93., -58.,  -2., -96.],
       [-34., -58., -32.,  -8.],
       [ -3., -40., -73., -43.],
       [-77., -92., -31., -21.]])

In [38]:
A + A

array([[186., 116.,   4., 192.],
       [ 68., 116.,  64.,  16.],
       [  6.,  80., 146.,  86.],
       [154., 184.,  62.,  42.]])

In [39]:
v = np.arange(4)

In [40]:
v

array([0, 1, 2, 3])

In [41]:
A @ v

array([350., 146., 315., 217.])

In [42]:
v @ A

array([271., 414., 271., 157.])

In [43]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [45]:
A.T.T

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
A.T.T == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
(A.T.T == A).all()

True

# Matrix arithmetic

In [48]:
A = np.arange(9).reshape(3,3)
print("A:\n", A)

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
B = np.round(10*np.random.random((3,3)))
print("B:\n", B)

B:
 [[4. 4. 3.]
 [1. 1. 6.]
 [2. 5. 3.]]


In [50]:
C = A + B
print("C:\n", C)

C:
 [[ 4.  5.  5.]
 [ 4.  5. 11.]
 [ 8. 12. 11.]]


<b>A and B are n-by-n matrices.
What's the asymptotic complexity of A + B, as O(...)?

In [51]:
print("A:\n", A)
print("B:\n", B)

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
B:
 [[4. 4. 3.]
 [1. 1. 6.]
 [2. 5. 3.]]


In [52]:
C = A @ B
print("C:\n", C)

C:
 [[ 5. 11. 12.]
 [26. 41. 48.]
 [47. 71. 84.]]


<b>A and B are n-by-n matrices.
What's the asymptotic complexity of A @ B, as O(...)?

In [53]:
C = A * B
print("C:\n", C)

C:
 [[ 0.  4.  6.]
 [ 3.  4. 30.]
 [12. 35. 24.]]


In [54]:
x = np.array([3,1,4])
print("A:\n", A)
print("\nx:", x)

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

x: [3 1 4]


In [55]:
y = A @ x
print("y:", y)

y: [ 9 33 57]


<b>A is an n-by-n matrix, and x is an n-vector.
What's the asymptotic complexity of A @ x, as O(...)?

In [56]:
z = x @ A
print("z:", z)

z: [27 35 43]


In [57]:
a = npla.norm(x)
print("x:", x, ", norm(x):", a)

x: [3 1 4] , norm(x): 5.0990195135927845


<b>x is an n-vector.
What's the asymptotic complexity of npla.norm(x), as O(...)?

# Interesting matrices

<b> All-zero and all-ones matrices. (Not too interesting.)

In [58]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<b>Identity matrix

In [60]:
I = np.eye(4)
print("I:\n", I)


I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
A = np.round(10*np.random.random((4,4)))
print("A:\n", A)
print()
print("I @ A:\n", I @ A)
print()
print("A @ I:\n", A @ I)

A:
 [[ 9.  3. 10.  3.]
 [10.  7.  9.  4.]
 [ 0.  3.  4.  1.]
 [10.  6.  5.  2.]]

I @ A:
 [[ 9.  3. 10.  3.]
 [10.  7.  9.  4.]
 [ 0.  3.  4.  1.]
 [10.  6.  5.  2.]]

A @ I:
 [[ 9.  3. 10.  3.]
 [10.  7.  9.  4.]
 [ 0.  3.  4.  1.]
 [10.  6.  5.  2.]]


<b>Diagonal matrix

In [62]:
D = np.diag([2, 1, .5, 0])
print("D:\n", D)

D:
 [[2.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0. ]]


Multiplying *A* on the left by a diagonal matrix scales the rows of *A*, and multiplying on the right by a diagonal scales the columns.

In general, multiplying *A* by another matrix on the left (*BA*) does something to the rows of *A*, and multiplying on the right (*AB*) does something to columns of *A*.

In [63]:
print("A:\n", A)
print()
print("D @ A:\n", D @ A)
print()
print("A @ D:\n", A @ D)

A:
 [[ 9.  3. 10.  3.]
 [10.  7.  9.  4.]
 [ 0.  3.  4.  1.]
 [10.  6.  5.  2.]]

D @ A:
 [[18.   6.  20.   6. ]
 [10.   7.   9.   4. ]
 [ 0.   1.5  2.   0.5]
 [ 0.   0.   0.   0. ]]

A @ D:
 [[18.   3.   5.   0. ]
 [20.   7.   4.5  0. ]
 [ 0.   3.   2.   0. ]
 [20.   6.   2.5  0. ]]


<b>Lower triangular matrix

In [64]:
L = np.tril(A)
print(L)

[[ 9.  0.  0.  0.]
 [10.  7.  0.  0.]
 [ 0.  3.  4.  0.]
 [10.  6.  5.  2.]]


<b>Unit lower triangular matrix

In [65]:
L = np.array([[1,0,0,0], [1,1,0,0], [2,0,1,0], [-1,2,1,1]])
print("L:\n", L)

L:
 [[ 1  0  0  0]
 [ 1  1  0  0]
 [ 2  0  1  0]
 [-1  2  1  1]]


# Unit lower triangular solve

In [66]:
b = np.array([2,3,3,1])
print("b:", b)

b: [2 3 3 1]


In [67]:
x = npla.solve(L,b)
print("x:", x)

x: [ 2.  1. -1.  2.]


In [68]:
x = cs111.Lsolve(L,b)
print("x:", x)

x: [ 2.  1. -1.  2.]


In [69]:
print(L @ x)

[2. 3. 3. 1.]


<b>L is an n-by-n unit lower triangular matrix, and b is an n-vector.<br>
What's the asymptotic complexity of x = cs111.Lsolve(L, b), as O(...)?