# In-class transcript from lecture 3, Jan 19, 2023


In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2023-winter/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

##########################################################
# If this import for matplotlib doesn't work, try saying #
#   conda install -c conda-forge ipympl                  #
# at a shell prompt on your computer                     #
##########################################################
import matplotlib
%matplotlib ipympl

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d




np.set_printoptions(precision = 4)

# Permuting a vector

In [2]:
# Here's a vector we can practice on, with n = 5

v = np.array([3.1, 4.1, 5.9, 2.6, 5.3])
print("v:", v)

v: [3.1 4.1 5.9 2.6 5.3]


In [3]:
# Here's our example of a 5-permutation p (lower case p)

p = [3, 0, 4, 1, 2]
print("p:", p)

p: [3, 0, 4, 1, 2]


In [4]:
# Permute the vector with the permutation

print("v[p]:", v[p])

v[p]: [2.6 3.1 5.3 4.1 5.9]


In [5]:
# Here's our example of a 5-by-5 permutation matrix P (upper case P)

P = np.array([[0,0,0,1,0], [1,0,0,0,0], [0,0,0,0,1], [0,1,0,0,0], [0,0,1,0,0]])

print(P)

[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [6]:
# Permute the vector with the matrix

print("P @ v:", P @ v)

P @ v: [2.6 3.1 5.3 4.1 5.9]


In [7]:
# Here's another permutation we'll call pinv:

pinv = [1, 3, 4, 0, 2]
print("pinv:", pinv)

pinv: [1, 3, 4, 0, 2]


In [8]:
# Permute the vector with pinv -- it's different

print("v:      ", v)
print("v[p]:   ", v[p])
print("v[pinv]:", v[pinv])

v:       [3.1 4.1 5.9 2.6 5.3]
v[p]:    [2.6 3.1 5.3 4.1 5.9]
v[pinv]: [4.1 2.6 5.3 3.1 5.9]


In [9]:
# pinv is the inverse permutation of p

vp = v[p]
w = vp[pinv]
print('v[p][pinv]:', w)

v[p][pinv]: [3.1 4.1 5.9 2.6 5.3]


In [10]:
v[p][pinv]

array([3.1, 4.1, 5.9, 2.6, 5.3])

In [11]:
# How do we get the  matrix for the inverse permutation?
# It's just the transpose!

P

array([[0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [12]:
P.T

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [13]:
print("v[pinv]:", v[pinv])
print("P.T @ v:", P.T @ v)

v[pinv]: [4.1 2.6 5.3 3.1 5.9]
P.T @ v: [4.1 2.6 5.3 3.1 5.9]


In [ ]:
print("P.T @ P @ v:", P.T @ P @ v)

In [14]:
# The matrix of the inverse perm is also the inverse matrix!

P.T @ P

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
P @ P.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Permuting a matrix

In [16]:
# Let's get a 5-by-5 matrix to experiment with

A = (20*np.random.random((5,5))).round()

A

array([[ 3.,  9.,  3.,  1., 15.],
       [ 7., 11., 19., 12., 20.],
       [ 3.,  9., 14.,  3., 10.],
       [ 6., 15.,  9.,  3., 19.],
       [ 4.,  2., 10.,  3., 10.]])

In [17]:
# Permute the rows of A with the permutation

print("p:", p)

p: [3, 0, 4, 1, 2]


In [18]:
A[p,:]

array([[ 6., 15.,  9.,  3., 19.],
       [ 3.,  9.,  3.,  1., 15.],
       [ 4.,  2., 10.,  3., 10.],
       [ 7., 11., 19., 12., 20.],
       [ 3.,  9., 14.,  3., 10.]])

In [19]:
# Permute the rows of A with the permutation matrix

P

array([[0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [20]:
P @ A

array([[ 6., 15.,  9.,  3., 19.],
       [ 3.,  9.,  3.,  1., 15.],
       [ 4.,  2., 10.,  3., 10.],
       [ 7., 11., 19., 12., 20.],
       [ 3.,  9., 14.,  3., 10.]])

In [21]:
A

array([[ 3.,  9.,  3.,  1., 15.],
       [ 7., 11., 19., 12., 20.],
       [ 3.,  9., 14.,  3., 10.],
       [ 6., 15.,  9.,  3., 19.],
       [ 4.,  2., 10.,  3., 10.]])

In [22]:
# Permute the columns of A with p

A[:,p]

array([[ 1.,  3., 15.,  9.,  3.],
       [12.,  7., 20., 11., 19.],
       [ 3.,  3., 10.,  9., 14.],
       [ 3.,  6., 19., 15.,  9.],
       [ 3.,  4., 10.,  2., 10.]])

In [23]:
# Multiplying A on the right by P affects the columns of A ...
A @ P

array([[ 9.,  1., 15.,  3.,  3.],
       [11., 12., 20.,  7., 19.],
       [ 9.,  3., 10.,  3., 14.],
       [15.,  3., 19.,  6.,  9.],
       [ 2.,  3., 10.,  4., 10.]])

In [24]:
# ... But that's not the column permutation we wanted!

# We need to use P.T on the right if we used P on the left

A @ P.T

array([[ 1.,  3., 15.,  9.,  3.],
       [12.,  7., 20., 11., 19.],
       [ 3.,  3., 10.,  9., 14.],
       [ 3.,  6., 19., 15.,  9.],
       [ 3.,  4., 10.,  2., 10.]])

In [25]:
A

array([[ 3.,  9.,  3.,  1., 15.],
       [ 7., 11., 19., 12., 20.],
       [ 3.,  9., 14.,  3., 10.],
       [ 6., 15.,  9.,  3., 19.],
       [ 4.,  2., 10.,  3., 10.]])

In [26]:
# We can permute the rows and columns symmetrically using p

A[p,:][:,p]

array([[ 3.,  6., 19., 15.,  9.],
       [ 1.,  3., 15.,  9.,  3.],
       [ 3.,  4., 10.,  2., 10.],
       [12.,  7., 20., 11., 19.],
       [ 3.,  3., 10.,  9., 14.]])

In [27]:
# Or we can permute the rows and columns symmetrically using P

P @ A @ P.T

array([[ 3.,  6., 19., 15.,  9.],
       [ 1.,  3., 15.,  9.,  3.],
       [ 3.,  4., 10.,  2., 10.],
       [12.,  7., 20., 11., 19.],
       [ 3.,  3., 10.,  9., 14.]])

# Lower triangular matrix

In [28]:
A = np.round(10*np.random.random((4,4)))
print("A:\n", A)

A:
 [[ 9. 10.  2.  8.]
 [ 3.  7.  2.  8.]
 [ 6.  5.  5.  4.]
 [10.  9.  6.  5.]]


In [29]:
L = np.tril(A)
print("L:\n", L)

L:
 [[ 9.  0.  0.  0.]
 [ 3.  7.  0.  0.]
 [ 6.  5.  5.  0.]
 [10.  9.  6.  5.]]


# Unit lower triangular matrix

In [30]:
L = np.array([[1,0,0,0], [1,1,0,0], [2,0,1,0], [-1,2,1,1]])
print("L:\n", L)

L:
 [[ 1  0  0  0]
 [ 1  1  0  0]
 [ 2  0  1  0]
 [-1  2  1  1]]


# Unit lower triangular solve

In [31]:
b = np.array([2,3,3,1])
print("b:", b)

b: [2 3 3 1]


In [32]:
x = npla.solve(L,b)
print("x:", x)

x: [ 2.  1. -1.  2.]


In [33]:
cs111.Lsolve(L,b)

array([ 2.,  1., -1.,  2.])

In [34]:
print(L @ x)

[2. 3. 3. 1.]
