# Transcript C from Lecture 7, February 2, 2023


In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2023-winter/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

##########################################################
# If this import for matplotlib doesn't work, try saying #
#   conda install -c conda-forge ipympl                  #
# at a shell prompt on your computer                     #
##########################################################
import matplotlib
# %matplotlib ipympl
# %matplotlib tk
%matplotlib inline

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d




np.set_printoptions(precision = 4)

# Jacobi iterative method for Ax = b (matrix view)

In [2]:
A = np.array([[3,-1,1],[-2,4,1],[1,0,-3]])
A

array([[ 3, -1,  1],
       [-2,  4,  1],
       [ 1,  0, -3]])

In [3]:
b = np.array([4,9,-8])
b

array([ 4,  9, -8])

In [4]:
npla.solve(A,b)

array([1., 2., 3.])

In [5]:
cs111.LUsolve(A,b)

(array([1., 2., 3.]), 0.0)

In [6]:
d = A.diagonal()
d

array([ 3,  4, -3])

In [7]:
D = np.diag(d)
D

array([[ 3,  0,  0],
       [ 0,  4,  0],
       [ 0,  0, -3]])

In [8]:
C = A - D
C

array([[ 0, -1,  1],
       [-2,  0,  1],
       [ 1,  0,  0]])

In [9]:
# initial guess x = 0

x = np.zeros(3)
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [0. 0. 0.]
relres: 1.0


In [10]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.3333 2.25   2.6667]
relres: 0.11009281484864232


In [11]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.1944 2.25   3.1111]
relres: 0.06772367705848906


In [12]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.0463 2.0694 3.0648]
relres: 0.025228572791021472


In [13]:
x = np.zeros(3)
for i in range(25):
    x = (b - C@x) / d
    relres = npla.norm(A@x-b)/npla.norm(b)
    print('iteration', i, 'x:', x, ', relres:' ,relres)

iteration 0 x: [1.3333 2.25   2.6667] , relres: 0.11009281484864232
iteration 1 x: [1.1944 2.25   3.1111] , relres: 0.06772367705848906
iteration 2 x: [1.0463 2.0694 3.0648] , relres: 0.025228572791021472
iteration 3 x: [1.0015 2.0069 3.0154] , relres: 0.004848508554135736
iteration 4 x: [0.9972 1.9969 3.0005] , relres: 0.0007097510453110915
iteration 5 x: [0.9988 1.9985 2.9991] , relres: 0.0004588144763188235
iteration 6 x: [0.9998 1.9996 2.9996] , relres: 0.00014805175855479684
iteration 7 x: [1.     2.     2.9999] , relres: 1.8326292927075283e-05
iteration 8 x: [1. 2. 3.] , relres: 5.524772159080887e-06
iteration 9 x: [1. 2. 3.] , relres: 3.3135499185529306e-06
iteration 10 x: [1. 2. 3.] , relres: 6.532135347878024e-07
iteration 11 x: [1. 2. 3.] , relres: 1.0924086459857045e-07
iteration 12 x: [1. 2. 3.] , relres: 5.901112667060393e-08
iteration 13 x: [1. 2. 3.] , relres: 1.4753632319085098e-08
iteration 14 x: [1. 2. 3.] , relres: 5.375393148821618e-09
iteration 15 x: [1. 2. 3.] , r

In [14]:
x, rr = cs111.Jsolve(A,b)

In [15]:
x

array([1., 2., 3.])

In [16]:
rr

[1.0,
 0.11009281484864232,
 0.06772367705848906,
 0.025228572791021472,
 0.004848508554135736,
 0.0007097510453110915,
 0.00045881447631884156,
 0.00014805175855482053,
 1.8326292927075283e-05,
 5.5247721590329305e-06,
 3.3135499185794736e-06,
 6.532135347878024e-07,
 1.0924086459857045e-07,
 5.9011126647527464e-08,
 1.4753632319085098e-08,
 5.375393037573431e-09]

In [17]:
cs111.Jsolve?

# What can go wrong with Jacobi?

In [18]:
# What could go wrong?
A = np.array([[5,2,3],[4,5,6],[3,4,3]])
print('A:\n',A)

A:
 [[5 2 3]
 [4 5 6]
 [3 4 3]]


In [19]:
b = A @ np.array([1,1,1])
print('b:', b)

b: [10 15 10]


In [20]:
npla.solve(A,b)

array([1., 1., 1.])

In [21]:
d = A.diagonal()
D = np.diag(d)
C = A-D
C

array([[0, 2, 3],
       [4, 0, 6],
       [3, 4, 0]])

In [22]:
d

array([5, 5, 3])

In [23]:
# initial guess x = 0
x = np.zeros(3)
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [0. 0. 0.]
relres: 1.0


In [24]:
# try to improve the guess, matrix version
x = (b - C@x) / d     # divide vector elementwise by d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.     3.     3.3333]
relres: 1.791483118733158


In [25]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [-1.2    -2.6    -2.6667]
relres: 3.1652822567199093


In [26]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [4.64 7.16 8.  ]
relres: 5.632910354232839


In [27]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [ -5.664  -10.312  -10.8533]
relres: 9.982717172487776


In [28]:
x, rr = cs111.Jsolve(A,b)

In [29]:
x

array([-1.1051e+249, -1.8668e+249, -2.0248e+249])

In [30]:
len(rr)


1001

In [33]:
rr[0:1000:100]

[1.0,
 8.409016320467502e+24,
 7.028164465484237e+49,
 5.874063489883822e+74,
 4.90947843532127e+99,
 4.10328872821926e+124,
 3.4294841313483545e+149,
 inf,
 inf,
 inf]

# Jacobi on the temperature problem

In [ ]:
# Jacobi on the temperature problem
k = 100
A = cs111.make_A(k)
b = cs111.make_b(k, right=cs111.radiator(k))

In [ ]:
A.shape

In [ ]:
A.nnz

In [ ]:
plt.spy(A)

In [ ]:
t = scipy.sparse.linalg.spsolve(A,b)
t.shape

In [ ]:
T = t.reshape(k, k)
plt.figure()
plt.imshow(T, cmap=cm.hot)
plt.xlabel('x0')
plt.ylabel('x1')
plt.title('Temperature by scipy.sparse.linalg.spsolve')

In [ ]:
t, resvec = cs111.Jsolve(A,b, max_iters=10)
resvec

In [ ]:
t.shape

In [ ]:
T = t.reshape(k, k)
plt.figure()
plt.imshow(T, cmap=cm.hot)
plt.xlabel('x0')
plt.ylabel('x1')
plt.title('Temperature by Jacobi, 10 iterations')

In [ ]:
iters = 10
t, resvec = cs111.Jsolve(A,b, max_iters=iters)
resvec[-1]

In [ ]:
T = t.reshape(k, k)
plt.figure()
plt.imshow(T, cmap=cm.hot)
plt.xlabel('x0')
plt.ylabel('x1')
plt.title(f'Temperature by Jacobi, {len(resvec)-1} iterations')

In [ ]:
# Plot relative residual norm as a function of iteration for Jacobi
%matplotlib inline
plt.figure()

(xJ,resvecJ) = cs111.Jsolve(A, b, tol = 1e-6, max_iters = 10000)
print('\nJacobi iters:', len(resvecJ)-1)
print('last rel res:', resvecJ[-1])
print('computed rel res:', npla.norm(A@xJ - b) / npla.norm(b))
plt.semilogy(resvecJ, label = 'Jacobi')

plt.legend()
plt.xlabel('iterations')
plt.ylabel('relative residual')
plt.title('Iterative methods for temperature problem with n = %d' % A.shape[0])