# Transcript B from Lecture 7, February 2, 2023


In [2]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2023-winter/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

##########################################################
# If this import for matplotlib doesn't work, try saying #
#   conda install -c conda-forge ipympl                  #
# at a shell prompt on your computer                     #
##########################################################
import matplotlib
%matplotlib ipympl

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d




np.set_printoptions(precision = 4)

# Jacobi iterative method for Ax = b

In [3]:
A = np.array([[3,1],[-2,4]])
A

array([[ 3,  1],
       [-2,  4]])

In [4]:
b = np.array([9,8])
b

array([9, 8])

In [5]:
npla.solve(A,b)

array([2., 3.])

In [6]:
cs111.LUsolve(A,b)

(array([2., 3.]), 0.0)

In [7]:
# Start the iteration with x = 0 as our first guess
x = np.zeros(2)
x

array([0., 0.])

In [8]:
# How good is x? Compute the relative residual norm
relres = npla.norm(b - A@x) / npla.norm(b)
relres

1.0

In [9]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [3. 2.]
relres: 0.5252257314388903


In [10]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.3333 3.5   ]
relres: 0.1666666666666666


In [11]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.8333 3.1667]
relres: 0.08753762190648182


In [12]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.9444 2.9167]
relres: 0.027777777777777832


In [13]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.0278 2.9722]
relres: 0.014589603651080349


In [14]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.0093 3.0139]
relres: 0.00462962962962965


In [15]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.9954 3.0046]
relres: 0.00243160060851345


In [16]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.9985 2.9977]
relres: 0.0007716049382715942


In [17]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.0008 2.9992]
relres: 0.0004052667680856294


In [18]:
# Try to improve the guess
x = np.array([(9-x[1])/3, (8+2*x[0])/4])
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.0003 3.0004]
relres: 0.0001286008230453045


In [19]:
npla.cond(A)

1.4560832005096076

# Matrix view of Jacobi

In [20]:
A

array([[ 3,  1],
       [-2,  4]])

In [21]:
d = A.diagonal()
d

array([3, 4])

In [22]:
D = np.diag(d)
D

array([[3, 0],
       [0, 4]])

In [23]:
C = A - D
C

array([[ 0,  1],
       [-2,  0]])

In [24]:
# initial guess x = 0
x = np.zeros(2)
x

array([0., 0.])

In [25]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [3. 2.]
relres: 0.5252257314388903


In [26]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [2.3333 3.5   ]
relres: 0.1666666666666666


In [27]:
# try to improve the guess, matrix version
x = (b - C@x) / d
print('x:',x)

relres = npla.norm(A@x-b)/npla.norm(b)
print('relres:',relres)

x: [1.8333 3.1667]
relres: 0.08753762190648182


In [28]:
x = np.zeros(2)
for i in range(25):
    x = (b - C@x) / d
    relres = npla.norm(A@x-b)/npla.norm(b)
    print('iteration', i, 'x:', x, ', relres:' ,relres)

iteration 0 x: [3. 2.] , relres: 0.5252257314388903
iteration 1 x: [2.3333 3.5   ] , relres: 0.1666666666666666
iteration 2 x: [1.8333 3.1667] , relres: 0.08753762190648182
iteration 3 x: [1.9444 2.9167] , relres: 0.027777777777777832
iteration 4 x: [2.0278 2.9722] , relres: 0.014589603651080349
iteration 5 x: [2.0093 3.0139] , relres: 0.00462962962962965
iteration 6 x: [1.9954 3.0046] , relres: 0.00243160060851345
iteration 7 x: [1.9985 2.9977] , relres: 0.0007716049382715942
iteration 8 x: [2.0008 2.9992] , relres: 0.0004052667680856294
iteration 9 x: [2.0003 3.0004] , relres: 0.0001286008230453045
iteration 10 x: [1.9999 3.0001] , relres: 6.754446134775651e-05
iteration 11 x: [2.     2.9999] , relres: 2.143347050755075e-05
iteration 12 x: [2. 3.] , relres: 1.1257410224711609e-05
iteration 13 x: [2. 3.] , relres: 3.572245084626502e-06
iteration 14 x: [2. 3.] , relres: 1.8762350374519347e-06
iteration 15 x: [2. 3.] , relres: 5.953741808037523e-07
iteration 16 x: [2. 3.] , relres: 3.12