# Transcript from Lecture, February 9, 2023

In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2023-winter/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import cs111

##########################################################
# If this import for matplotlib doesn't work, try saying #
#   conda install -c conda-forge ipympl                  #
# at a shell prompt on your computer                     #
##########################################################
import matplotlib
%matplotlib ipympl

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d




np.set_printoptions(precision = 4)

# Vector dot products and perpendicular (orthogonal) vectors

In [2]:
x = np.array([3, 1, 4, -3])
y = np.array([1, 2, -1 , 1])

print('x:', x)
print('y:', y)

x: [ 3  1  4 -3]
y: [ 1  2 -1  1]


In [3]:
np.dot(x,y)

-2

In [4]:
x.dot(y)

-2

In [5]:
x.T @ y

-2

In [6]:
x @ y

-2

In [7]:
x.T @ x

35

In [8]:
npla.norm(x,2)

5.916079783099616

In [9]:
npla.norm(x,2) ** 2

35.0

<b> Two vectors x and y are *orthogonal* (perpendicular) if x.T @ y = 0

In [10]:
x

array([ 3,  1,  4, -3])

In [11]:
y = np.array([1, 4, -1 ,1])
y

array([ 1,  4, -1,  1])

In [12]:
x.T @ y

0

In [13]:
x.dot(y)

0

# Orthogonal matrices

<b> The square matrix A is *orthogonal* if A.T @ A = I, the identity matrix.

The inverse of an orthogonal matrix is its transpose.

Therefore, the transpose of an orthogonal matrix is also orthogonal.

In [14]:
Q = cs111.random_orthog(5)
Q

array([[-0.2502,  0.1429,  0.2649, -0.5425, -0.7433],
       [ 0.4099, -0.2644,  0.7943,  0.3309, -0.1472],
       [-0.7294, -0.6455,  0.07  ,  0.2149, -0.0105],
       [ 0.4568, -0.7011, -0.2847, -0.4651, -0.0506],
       [-0.1694,  0.0385,  0.4614, -0.5777,  0.6505]])

In [15]:
Q.T @ Q

array([[ 1.0000e+00, -6.0715e-18,  6.9389e-17, -5.5511e-17, -2.7756e-17],
       [-6.0715e-18,  1.0000e+00,  1.2837e-16,  7.2858e-17,  5.5511e-17],
       [ 6.9389e-17,  1.2837e-16,  1.0000e+00, -1.1102e-16, -5.5511e-17],
       [-5.5511e-17,  7.2858e-17, -1.1102e-16,  1.0000e+00, -5.5511e-17],
       [-2.7756e-17,  5.5511e-17, -5.5511e-17, -5.5511e-17,  1.0000e+00]])

In [16]:
I = np.eye(5)
npla.norm(Q.T @ Q - I, 2)

4.444916836573678e-16

<b>Every column of an orthogonal matrix is a unit vector (a vector of length one)

In [17]:
v = Q[:, 2]
npla.norm(v, 2)

0.9999999999999999

<b> Any two different columns of an orthogonal matrix are perpendicular

In [18]:
w = Q[:,1]
v.T @ w

1.2836953722228372e-16

<b>The identity matrix is orthogonal

In [19]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
I.T @ I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<b>Permutation matrices are orthogonal

In [21]:
P = np.array([[0,0,1,0,0], [1,0,0,0,0], [0,1,0,0,0], [0,0,0,0,1], [0,0,0,1,0]])
P

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]])

In [22]:
P.T

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]])

In [23]:
P @ P.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# An orthogonal matrix doesn't change the length of a vector

In [24]:
Q = cs111.random_orthog(5)
Q

array([[-0.1472, -0.8656, -0.0634,  0.4735, -0.0298],
       [ 0.3667, -0.0174,  0.4862,  0.1956,  0.7685],
       [-0.2522, -0.248 , -0.4885, -0.5614,  0.5666],
       [-0.5816, -0.1506,  0.706 , -0.3665, -0.0793],
       [-0.6648,  0.4079, -0.1501,  0.5366,  0.2849]])

In [25]:
v = np.random.random(5)
print('v:', v, 'norm(v):', npla.norm(v,2))

v: [0.1948 0.2374 0.415  0.143  0.7135] norm(v): 0.8922732092203605


In [26]:
w = Q @ v
print('w:', w, 'norm(w):', npla.norm(w,2))

w: [-0.214   0.8454  0.0133  0.0349  0.185 ] norm(w): 0.8922732092203605


<b> Therefore, the 2-norm and 2-condition number of an orthogonal matrix are both 1

In [27]:
Q = cs111.random_orthog(5)
Q

array([[-0.3263, -0.2938,  0.0307,  0.8837, -0.1592],
       [-0.4193, -0.3592, -0.0547, -0.4035, -0.7276],
       [ 0.7258, -0.0633, -0.4814,  0.1823, -0.4519],
       [-0.3664,  0.7962, -0.4204,  0.1063, -0.2093],
       [-0.2381, -0.383 , -0.7665, -0.1086,  0.4441]])

In [28]:
Q.T @ Q

array([[1.0000e+00, 5.5511e-17, 0.0000e+00, 6.9389e-18, 1.3878e-17],
       [5.5511e-17, 1.0000e+00, 1.1102e-16, 1.5959e-16, 1.9429e-16],
       [0.0000e+00, 1.1102e-16, 1.0000e+00, 2.7756e-17, 1.1102e-16],
       [6.9389e-18, 1.5959e-16, 2.7756e-17, 1.0000e+00, 4.1633e-17],
       [1.3878e-17, 1.9429e-16, 1.1102e-16, 4.1633e-17, 1.0000e+00]])

In [29]:
npla.norm(Q, 2)

1.0000000000000004

In [30]:
npla.cond(Q, 2)

1.0000000000000007

In [31]:
# Only the 2-norm, not the others!
npla.norm(Q, 1)

2.0758901012397124

# Solving a linear system with an orthogonal matrix

In [32]:
Q = cs111.random_orthog(5)
Q

array([[-0.2333,  0.0377, -0.0653,  0.8783, -0.4105],
       [-0.1511, -0.242 ,  0.4886, -0.3437, -0.7495],
       [ 0.1681, -0.9563, -0.047 ,  0.1618,  0.1701],
       [-0.0746, -0.087 , -0.8688, -0.2678, -0.4004],
       [-0.9428, -0.1341, -0.0018, -0.1122,  0.2837]])

In [33]:
x_exact = np.ones(5)
b = Q @ x_exact
print('x_exact:', x_exact)
print('b:      ', b)

x_exact: [1. 1. 1. 1. 1.]
b:       [ 0.2069 -0.9978 -0.5033 -1.6985 -0.9073]


In [34]:
npla.norm(x_exact) - npla.norm(b)

0.0

In [35]:
x = Q.T @ b
x

array([1., 1., 1., 1., 1.])

In [36]:
npla.norm(x_exact) - npla.norm(x)

0.0

In [37]:
error = x_exact - x
residual = b - Q @ x

print("relative residual norm:", npla.norm(residual,2)/npla.norm(b,2))
print("relative error norm:   ", npla.norm(error,2)/npla.norm(x_exact,2))


relative residual norm: 2.6852712547870863e-16
relative error norm:    2.3288234633381846e-16


<b> Why not exactly equal? Wait for floating-point arithmetic lecture!
