# Transcript from Lecture, February 28, 2023

In [1]:
import sys

########################################
# Change the string in the line below! #
########################################
sys.path.append("/Users/gilbert/Documents/CS111-2023-winter/Python") 

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import linalg as spla
import scipy.sparse
import scipy.sparse.linalg
from scipy import integrate
import networkx as nx
import json
import cs111

#######################################################
# Here are three different ways to have plots appear. #
# Uncomment the one you want to use.                  #
#                                                     #
# inline    : static plot in notebook                 #
# ipympl    : plot in notebook with pan/zoom controls #
# tk        : plot in popup window with pan/zoom      #
#                                                     #
# If %matplotlib ipympl doesn't work, try saying:     #
#   conda install -c conda-forge ipympl               #
# at a shell prompt.                                  #
#######################################################
import matplotlib
%matplotlib inline 
# %matplotlib ipympl
# %matplotlib tk 

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d

np.set_printoptions(precision = 4)

# Eigenvalues and eigenvectors

If $w$ is a nonzero vector and $\lambda$ is a number and $Aw = \lambda w$, we say $w$ is an *eigenvector* of $A$ with *eigenvalue* $\lambda$. Notice that in this case any nonzero multiple of $w$ is also an eigenvector.

Every matrix has at least one eigenvalue/eigenvector, and an $n$-by-$n$ matrix has at most $n$ linearly independent eigenvectors.

In [2]:
A = np.diag([1,2,3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [3]:
lam, W = spla.eig(A)
print('lam:', lam)
print('W:')
print(W)

lam: [1.+0.j 2.+0.j 3.+0.j]
W:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# An eigenvalue can be zero (but an eigenvector can't be the zero vector)

A[1,1] = 0
A

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 3]])

In [5]:
# An eigenvalue can be zero (but an eigenvector can't be the zero vector)

lam, W = spla.eig(A)
print('lam:', lam)
print('W:')
print(W)

lam: [1.+0.j 0.+0.j 3.+0.j]
W:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# A real matrix can have complex eigenvalues and eigenvectors

A = np.array([[0,1,0,0], [0,0,1,0], [0,0,0,1], [1,0,0,0]])
A

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [7]:
lam, W = spla.eig(A)
print('lam:', lam)
print('W:')
print(W)

lam: [-1.0000e+00+0.j -5.5511e-17+1.j -5.5511e-17-1.j  1.0000e+00+0.j]
W:
[[-5.0000e-01+0.0000e+00j  5.0000e-01+0.0000e+00j  5.0000e-01-0.0000e+00j
  -5.0000e-01+0.0000e+00j]
 [ 5.0000e-01+0.0000e+00j -3.0531e-16+5.0000e-01j -3.0531e-16-5.0000e-01j
  -5.0000e-01+0.0000e+00j]
 [-5.0000e-01+0.0000e+00j -5.0000e-01-1.1102e-16j -5.0000e-01+1.1102e-16j
  -5.0000e-01+0.0000e+00j]
 [ 5.0000e-01+0.0000e+00j  1.9429e-16-5.0000e-01j  1.9429e-16+5.0000e-01j
  -5.0000e-01+0.0000e+00j]]


In [8]:
A = np.random.rand(4,4)
print('A:'); print(A)
print()

lam, W = spla.eig(A)
print('lam:', lam)
print('W:'); print(W)

A:
[[0.4643 0.0637 0.1792 0.7695]
 [0.0935 0.9746 0.3868 0.0665]
 [0.6401 0.5639 0.5664 0.1074]
 [0.6955 0.6965 0.0234 0.7889]]

lam: [ 1.7315+0.j     -0.27  +0.j      0.6664+0.0487j  0.6664-0.0487j]
W:
[[-0.4717+0.j     -0.6563+0.j      0.6283+0.0018j  0.6283-0.0018j]
 [-0.3665+0.j     -0.1439+0.j     -0.6679+0.j     -0.6679-0.j    ]
 [-0.4947+0.j      0.5333+0.j      0.3569-0.0952j  0.3569+0.0952j]
 [-0.6312+0.j      0.514 +0.j      0.1371+0.0624j  0.1371-0.0624j]]


In [9]:
i = 2
val = lam[i]
val

(0.6663539836228751+0.04866097875472126j)

In [10]:
vec = W[:,i]
vec

array([ 0.6283+0.0018j, -0.6679+0.j    ,  0.3569-0.0952j,  0.1371+0.0624j])

In [11]:
npla.norm(vec)

1.0

In [12]:
print('val * vec:', val * vec)
print('  A @ vec:', A @ vec)

val * vec: [ 0.4186+0.0318j -0.4451-0.0325j  0.2424-0.0461j  0.0883+0.0482j]
  A @ vec: [ 0.4186+0.0318j -0.4451-0.0325j  0.2424-0.0461j  0.0883+0.0482j]


In [13]:
# Any multiple of an eigenvector is an eigenvector (with the same eigenvalue)

vec2 = 2 * vec

print('val * vec2:', val * vec2)
print('  A @ vec2:', A @ vec2)

val * vec2: [ 0.8372+0.0636j -0.8901-0.065j   0.4849-0.0921j  0.1766+0.0965j]
  A @ vec2: [ 0.8372+0.0636j -0.8901-0.065j   0.4849-0.0921j  0.1766+0.0965j]


In [14]:
# An n-by-n matrix has at most n linearly independent eigenvectors, but can have fewer

A = np.array([[1,2,3], [0,1,2], [0,0,1]])

print('A:'); print(A)
print()

lam, W = spla.eig(A)
print('lam:', lam)
print('W:'); print(W)

A:
[[1 2 3]
 [0 1 2]
 [0 0 1]]

lam: [1.+0.j 1.+0.j 1.+0.j]
W:
[[ 1.0000e+00 -1.0000e+00  1.0000e+00]
 [ 0.0000e+00  1.1102e-16 -1.1102e-16]
 [ 0.0000e+00  0.0000e+00  1.2326e-32]]


In [15]:
# Can you see why all three eigenvectors above are "really" the same one?

The eigenvalues of $A$ and $A^T$ are the same, though the eigenvectors aren't necessarily the same.

In [16]:
A = np.random.rand(3,3)

print('A:'); print(A)
print()

lam, W = spla.eig(A)
print('lam:', lam)
print('W:'); print(W)

A:
[[0.7875 0.574  0.4177]
 [0.775  0.5924 0.9607]
 [0.6731 0.7215 0.8575]]

lam: [ 2.108 +0.j  0.2803+0.j -0.1508+0.j]
W:
[[-0.4697 -0.7871  0.357 ]
 [-0.6314  0.3058 -0.8559]
 [-0.6171  0.5356  0.3741]]


In [17]:
print('A.T:'); print(A.T)
print()

lam, W = spla.eig(A.T)
print('lam:', lam)
print('W:'); print(W)

A.T:
[[0.7875 0.775  0.6731]
 [0.574  0.5924 0.7215]
 [0.4177 0.9607 0.8575]]

lam: [ 2.108 +0.j  0.2803+0.j -0.1508+0.j]
W:
[[-0.6097 -0.7722  0.1512]
 [-0.517  -0.0451 -0.7462]
 [-0.6008  0.6338  0.6483]]


# Eigenvalues and eigenvectors of symmetric matrices

If $A$ is an $n$-by-$n$ symmetric matrix,
- All the eigenvalues of $A$ are real (no imaginary part)
- $A$ has $n$ linearly independent eigenvectors
- The eigenvectors can be chosen to be orthogonal to each other

Thus, $AW = WS$ holds where $W$ is an orthogonal matrix ($W^TW=I$) and $S$ is a square diagonal matrix. We can therefore write the eigenvalue equation as a matrix factorization:

$$A = WSW^T$$

We will write $S$ = diag($\lambda_0, \lambda_1, \ldots, \lambda_{n-1}$) with
$$\lambda_0 \le \lambda_1 \le \cdots \lambda_{n-1}.$$ 

Unfortunately, the standard convention is to number eigenvalues in increasing order and singular values in decreasing order.

We will write $w_i$ to mean column $i$ of $W$, so for all $0\le i < n$,
$$Aw_i = \lambda_i w_i$$


In [18]:
# Random symmetric matrix

A = np.random.randn(4,4)
A = A + A.T
A

array([[-1.0531, -2.1029, -1.4891, -2.1454],
       [-2.1029, -0.5885,  1.0159, -0.1263],
       [-1.4891,  1.0159, -3.876 , -1.0162],
       [-2.1454, -0.1263, -1.0162,  0.627 ]])

In [19]:
print('A:'); print(A)
print()

lam, W = spla.eig(A)
print('lam:', lam)
print('W:'); print(W)

A:
[[-1.0531 -2.1029 -1.4891 -2.1454]
 [-2.1029 -0.5885  1.0159 -0.1263]
 [-1.4891  1.0159 -3.876  -1.0162]
 [-2.1454 -0.1263 -1.0162  0.627 ]]

lam: [-5.1345+0.j -3.111 +0.j  2.639 +0.j  0.7158+0.j]
W:
[[-0.4951 -0.5487 -0.6519  0.1697]
 [-0.0588 -0.6579  0.4398 -0.6085]
 [-0.8027  0.4718  0.1232 -0.3435]
 [-0.3272 -0.2089  0.6053  0.6949]]


In [20]:
# Better! Use spla.eigh(A) not spla.eig(A) when A is symmetric

print('A:'); print(A)
print()

lam, W = spla.eigh(A)
print('lam:', lam)
print('W:'); print(W)

A:
[[-1.0531 -2.1029 -1.4891 -2.1454]
 [-2.1029 -0.5885  1.0159 -0.1263]
 [-1.4891  1.0159 -3.876  -1.0162]
 [-2.1454 -0.1263 -1.0162  0.627 ]]

lam: [-5.1345 -3.111   0.7158  2.639 ]
W:
[[-0.4951  0.5487  0.1697  0.6519]
 [-0.0588  0.6579 -0.6085 -0.4398]
 [-0.8027 -0.4718 -0.3435 -0.1232]
 [-0.3272  0.2089  0.6949 -0.6053]]


In [21]:
print('W.T @ W:\n', W.T @ W)
print()
print('norm W.T@W - I:', npla.norm(W.T@W - np.eye(4)))

W.T @ W:
 [[ 1.0000e+00 -2.2204e-16  5.5511e-17  1.1102e-16]
 [-2.2204e-16  1.0000e+00  1.1102e-16 -1.6653e-16]
 [ 5.5511e-17  1.1102e-16  1.0000e+00  1.1102e-16]
 [ 1.1102e-16 -1.6653e-16  1.1102e-16  1.0000e+00]]

norm W.T@W - I: 5.324442579404919e-16


In [22]:
S = np.diag(lam)
S

array([[-5.1345,  0.    ,  0.    ,  0.    ],
       [ 0.    , -3.111 ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.7158,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  2.639 ]])

In [23]:
A @ W

array([[ 2.5423, -1.7068,  0.1215,  1.7204],
       [ 0.3017, -2.0466, -0.4356, -1.1608],
       [ 4.1213,  1.4677, -0.2459, -0.3251],
       [ 1.6802, -0.6498,  0.4974, -1.5974]])

In [24]:
W @ S

array([[ 2.5423, -1.7068,  0.1215,  1.7204],
       [ 0.3017, -2.0466, -0.4356, -1.1608],
       [ 4.1213,  1.4677, -0.2459, -0.3251],
       [ 1.6802, -0.6498,  0.4974, -1.5974]])

In [25]:
W @ S @ W.T

array([[-1.0531, -2.1029, -1.4891, -2.1454],
       [-2.1029, -0.5885,  1.0159, -0.1263],
       [-1.4891,  1.0159, -3.876 , -1.0162],
       [-2.1454, -0.1263, -1.0162,  0.627 ]])

In [26]:
A

array([[-1.0531, -2.1029, -1.4891, -2.1454],
       [-2.1029, -0.5885,  1.0159, -0.1263],
       [-1.4891,  1.0159, -3.876 , -1.0162],
       [-2.1454, -0.1263, -1.0162,  0.627 ]])

# Symmetric positive definite (SPD) and positive semidefinite (SPSD) matrices

A symmetric matrix $A$ is *positive definite* if all its eigenvalues are positive, 
so $0 < \lambda_0 \le \lambda_1 \le \cdots \lambda_{n-1}$.
<br>A symmetric matrix $A$ is positive definite if and only if $x^TAx>0$ for all nonzero vectors $x$.

A symmetric matrix $A$ is *positive semidefinite* if all its eigenvalues are nonnegative,
so $0 \le \lambda_0 \le \lambda_1 \le \cdots \lambda_{n-1}$.
<br>A symmetric matrix $A$ is positive semidefinite if and only if $x^TAx\ge 0$ for all nonzero vectors $x$.


In [27]:
# One way to create an SPD matrix...

A = np.random.randn(4,4)
A = A.T @ A
print('A:'); print(A)

A:
[[ 3.0872 -1.91   -2.8977  1.7563]
 [-1.91    2.1748  0.8551 -2.6149]
 [-2.8977  0.8551  4.6063 -1.4281]
 [ 1.7563 -2.6149 -1.4281  5.3022]]


In [28]:
lam, W = spla.eigh(A)
print('lam:', lam)
print('W:')
print(W)

lam: [0.027  1.2964 4.1383 9.7087]
W:
[[ 0.6087 -0.5541  0.2846  0.4914]
 [ 0.6863  0.5511  0.2741 -0.3874]
 [ 0.3276 -0.4343 -0.6669 -0.5093]
 [ 0.2262  0.4479 -0.6318  0.5908]]


In [29]:
# Now make it semidefinite by shifting the eigenvalues by lambda_0

B = A - lam[0] * np.eye(4)

print('B:'); print(B)

B:
[[ 3.0602 -1.91   -2.8977  1.7563]
 [-1.91    2.1478  0.8551 -2.6149]
 [-2.8977  0.8551  4.5793 -1.4281]
 [ 1.7563 -2.6149 -1.4281  5.2752]]


In [30]:
npla.matrix_rank(B)

3

In [31]:
B @ W[:,0]

array([ 1.6653e-15, -6.6613e-16, -2.2204e-16,  1.3323e-15])

In [32]:
lam, W = spla.eigh(A)

print('lam for A:', lam)
print('W for A:'); print(W)

lam for A: [0.027  1.2964 4.1383 9.7087]
W for A:
[[ 0.6087 -0.5541  0.2846  0.4914]
 [ 0.6863  0.5511  0.2741 -0.3874]
 [ 0.3276 -0.4343 -0.6669 -0.5093]
 [ 0.2262  0.4479 -0.6318  0.5908]]


In [33]:
lam, W = spla.eigh(B)

print('lam for B:', lam)
print('W for B:'); print(W)

lam for B: [-4.3039e-16  1.2694e+00  4.1113e+00  9.6818e+00]
W for B:
[[ 0.6087  0.5541  0.2846  0.4914]
 [ 0.6863 -0.5511  0.2741 -0.3874]
 [ 0.3276  0.4343 -0.6669 -0.5093]
 [ 0.2262 -0.4479 -0.6318  0.5908]]
